### ISSUE TITLE
everything shows as None

### ISSUE THREAD

**Issue by dotada** [FlawCra/ReactSelfbot#1]
Everything shows as None except ;help

**Comment by dotada** [comment]
heres a pic
![image](https://user-images.githubusercontent.com/65085906/132232775-9d8be821-e5f4-4842-be19-c505dda61a9c.png)

**Comment by ForyxCraft** [comment]
Yeah thats a known bug but all commands should work.
Just have a look at the command list here: https://react.flawcra.cc/features.txt

**Comment by dotada** [comment]
> Yeah thats a known bug but all commands should work.
> Just have a look at the command list here: https://react.flawcra.cc/features.txt

Ok thanks
