### ISSUE TITLE
Crashing on startup (can't figure out why)

### ISSUE THREAD

**Issue by PhoenixAceVFX** [FlawCra/ReactSelfbot#11]
![raw (4)](https://user-images.githubusercontent.com/38572203/145658048-0d74aebb-c1e3-4d89-9ec3-19b02a656ab1.png)
I don't know whats going on but it's just been giving me this.

**Comment by ForyxCraft** [comment]
Ok this seems odd, can you try running from source in a [venv](https://docs.python.org/3/library/venv.html)?

**Comment by PhoenixAceVFX** [comment]
![image](https://user-images.githubusercontent.com/38572203/145685352-276c5ccc-d9d8-4b4a-8455-b23c9c277050.png)
I think i got it to run in a venv, im not sure cause i'm not too familiar with python

**Comment by PhoenixAceVFX** [comment]
is it possible its trying to find an exe in my system or something? if so i know how to fix that and just need to know what exes its looking for

**Comment by ForyxCraft** [comment]
I think you installed the venv incorrectly. Please look on youtube for a tutorial. (python did not find the venv folder)

**Comment by PhoenixAceVFX** [comment]
i have no clue how to use python for stuff like this

**Comment by PhoenixAceVFX** [comment]
does react need WMIC.exe?

**Comment by PhoenixAceVFX** [comment]
![image](https://user-images.githubusercontent.com/38572203/145688368-883a7b44-8a49-42b6-a964-d35ee61d3a2a.png)
yea it looks like it needed wmic
now i need to figure out this error

**Comment by PhoenixAceVFX** [comment]
nevermind it functions perfect now xD

**Comment by PhoenixAceVFX** [comment]
so it just needed wmic.exe which since my antivirus is protecting it i had to exception it

**Comment by PhoenixAceVFX** [comment]
or i think it is
its throwing errors for everything

**Comment by PhoenixAceVFX** [comment]
![image](https://user-images.githubusercontent.com/38572203/145688448-bc1de62a-1716-4b01-8799-39886e7e5070.png)

**Comment by ForyxCraft** [comment]
You should be able to ignore those get the full command list from https://reactselfbot.cc/features.txt

**Comment by PhoenixAceVFX** [comment]
aight awesome!

**Comment by PhoenixAceVFX** [comment]
holy crap this is ALOT

**Comment by PhoenixAceVFX** [comment]
aight yea everything is working then

**Comment by PhoenixAceVFX** [comment]
thanks for da help!
