### ISSUE TITLE
.py Just closes

### ISSUE THREAD

**Issue by Josh830-lab** [FlawCra/ReactSelfbot#4]
I installed all the requirements from the .txt both using the pip install -r /mypath/to/requirements.txt and manually doing pip install requirement_here and it still closes also tried entering my token in the main file still doesn't work

**Comment by Josh830-lab** [comment]
Also I downloaded the master file if that makes a difference

**Comment by LuaLighter** [comment]
same

**Comment by ForyxCraft** [comment]
I updated requirements.txt. You can try to install it again now. (on linux you'll have to remove `wmi` and change `aiohttp==3.7.4.post0` to `aiohttp`

**Comment by Josh830-lab** [comment]
Now it asks for "selfbot password" and "selfbot username"

**Comment by ForyxCraft** [comment]
> ![image](https://user-images.githubusercontent.com/72281255/136116375-1992a7dc-4059-4bd5-8c72-117e0ba1a89f.png) This happens now

does it bootloop? if so please wait a few hours until I get home again

**Comment by Josh830-lab** [comment]
@ForyxCraft 
![image](https://user-images.githubusercontent.com/72281255/136764230-f067d08f-0290-4ce6-a1d7-8f555de5bdb7.png)
Still says this with 1.4.2 but now it doesn't loopboot at least but it still won't let me pass

**Comment by Josh830-lab** [comment]
Yes I am @ForyxCraft

**Comment by Josh830-lab** [comment]
Using 1.4.2 using all requirements and it just closes

**Comment by minenightowl** [comment]
Im getting the same music error, and whenever i try to run a command it comes back empty. 

![image](https://user-images.githubusercontent.com/29973351/144290273-d7bd8171-5d63-47e4-8ab2-abf537e56b88.png)

Heres the console

![image](https://user-images.githubusercontent.com/29973351/144290315-8ed4e363-aae5-4e6d-b12b-b0d431a86e6c.png)

installed all the requirements using "pip install -r C:\Users\name\Desktop\Reactbot\requirements.txt" with no errors.
Using windows 11 with python 3.7.9

**Comment by ForyxCraft** [comment]
> Im getting the same music error, and whenever i try to run a command it comes back empty.
> 
> ![image](https://user-images.githubusercontent.com/29973351/144290273-d7bd8171-5d63-47e4-8ab2-abf537e56b88.png)
> 
> Heres the console
> 
> ![image](https://user-images.githubusercontent.com/29973351/144290315-8ed4e363-aae5-4e6d-b12b-b0d431a86e6c.png)
> 
> installed all the requirements using "pip install -r C:\Users\name\Desktop\Reactbot\requirements.txt" with no errors. Using windows 11 with python 3.7.9

This currently is a known issue.
You can work around this by just using the online command list [HERE](https://reactselfbot.cc/features.txt)

**Comment by minenightowl** [comment]
> > Im getting the same music error, and whenever i try to run a command it comes back empty.
> > *nuked for spam reasons
> > Heres the console
> > *nuked for spam reasons
> > installed all the requirements using "pip install -r C:\Users\name\Desktop\Reactbot\requirements.txt" with no errors. Using windows 11 with python 3.7.9
> 
> This currently is a known issue. You can work around this by just using the online command list [HERE](https://reactselfbot.cc/features.txt)

Awesome, thank you.
