### ISSUE TITLE
how to setup variables or tokens and other stuff?

### ISSUE THREAD

**Issue by amirulandalib** [FlawCra/ReactSelfbot#5]
how to setup variables or tokens and other stuff?

**Comment by PythonJoshua** [comment]
**Hello! I hope this helps:**

When ran for the first time, it should ask you for a token, and a prefix, without the "" around the token.
You can also manually do this in the config.json / config.txt file!

Almost all variables are in the config.json/txt file, I hope this helps, if you have any other questions I can try help if you reply to this comment :D

**Comment by amirulandalib** [comment]
> **Hello! I hope this helps:**
> 
> When ran for the first time, it should ask you for a token, and a prefix, without the "" around the token. You can also manually do this in the config.json / config.txt file!
> 
> Almost all variables are in the config.json/txt file, I hope this helps, if you have any other questions I can try help if you reply to this comment :D

yes i got it solved back thanks btw
